version: '2'
services:
  solr:
    command: solr-foreground -a "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    build: solr
    ports:
      - "8983:8983"
      - "18983:18983"
      - "8849:8849"
      - "1044:1044"
    volumes:
      - ..:/data
      - data-solr:/opt/solr/server/solr/ocrtest
      - ./google1000:/google1000
  iiif:
    command: /bin/iiif-server -host 0.0.0.0 -config /data/go-iiif-conf.json
    build: iiif
    volumes:
      - ./iiif:/data
      - ./google1000:/google1000
    ports:
      - "8080:8080"
  frontend:
    build: frontend
    ports:
      - "8181:80"

volumes:
  data-solr:
