include: "https://raw.githubusercontent.com/dbmdz/development/master/ci/.gitlab-ci-base.yml"

stages:
  - build
  - test
  - publish
  - release

publish_docs:
  stage: publish
  before_script:
    - git remote rm origin
    - git remote add origin "https://stefan-it:$GITHUB_TOKEN@github.com/$CI_PROJECT_PATH.git"
    - pip3 install mkdocs
  script:
    - mkdocs gh-deploy --force
  only:
    refs:
      - master

github_release:
  extends: .release
  only:
    - tags
  script:
    - if [[ "$CI_COMMIT_TAG" =~ .*RC.* ]]; then exit 0; fi
    - mvn clean package
    - hub release edit -m $CI_COMMIT_TAG -a target/solr-ocrhighlighting-${CI_COMMIT_TAG}.jar -t $CI_COMMIT_SHA $CI_COMMIT_TAG