site_name: Solr OCR Highlighting Plugin
theme: readthedocs
nav:
    - Introduction: index.md
    - Installation: installation.md
    - Indexing: indexing.md
    - Querying: query.md
    - Example Setup: example.md
    - Supported Formats: formats.md
markdown_extensions:
    - def_list
    - attr_list
    - fenced_code
    - admonition
    - smarty
repo_url: https://github.com/dbmdz/solr-ocrhighlighting/